### ISSUE TITLE
Error at spline_models.py (row: 659) when trying wave_test.py

### ISSUE THREAD

**Issue by Ryo-wtnb11** [aschethor/Spline_PINN#5]
Hi. I cannot try wave_test.py because superres_kernels[:,:,:,i::resolution_factor,j::resolution_factor] and kernels are not match size.
I think 

```
# before
kernels = kernels.reshape(1,1+2+1+1+1, 2*(orders[0]+1)*(orders[1]+1),2,2).detach().clone()
# after
kernels = kernels.reshape(1,1+2+1+1,2*(orders[0]+1)*(orders[1]+1),2,2).detach().clone()
```

is correct
Above code is working now.

**Comment by wandeln** [comment]
Hi, sorry for the very late reply. Thanks for pointing out this issue! It should be fixed by now :)
