### ISSUE TITLE
Space problems

### ISSUE THREAD

**Issue by dezenn** [aschethor/Spline_PINN#7]
Hello dear researchers!
I would like to test out your simulation but since I'm using Windows I run into the 'file name problem' as pointed out in the other issue thread. Training the PINN myself I come across some space issues. So I would be interest in the technical necessities to run your simulation. Maybe you can also name some low requirements regarding batch_size, n_batches and epochs to still run your simulation smoothly. I can not afford a high batch size. 

Best regards!

**Comment by wandeln** [comment]
Hi,

unfortunately, I'm not used to python development in windows but to address your issues, I would recommend the following:
1. file name problem: In line 30 of the Logger.py file, you can replace the problematic ":"-symbols by less problematic symbols (e.g. "-").
2. batch_size problem: you can change the batch_size by passing a batch_size argument (e.g. just append "--batch_size=20" when starting a new training). It might be necessary to lower the learning_rate in that case as well (using "--lr=..."). More information on the different parameters can be found using "--help" or inside the get_param.py file.

I hope that helps! :)

Best regards, Nils

**Comment by dezenn** [comment]
Hi Nils,

thanks for your advice. I already did the first and second step but i didn't change the lower rate so far. So i will try that. Thank you!
